<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto

namespace Mvccpb;

/**
 * Protobuf enum <code>mvccpb.Event.EventType</code>
 */
class Event_EventType
{
    /**
     * <code>PUT = 0;</code>
     */
    const PUT = 0;
    /**
     * <code>DELETE = 1;</code>
     */
    const DELETE = 1;
}

