<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf enum <code>etcdserverpb.AlarmRequest.AlarmAction</code>
 */
class AlarmRequest_AlarmAction
{
    /**
     * <code>GET = 0;</code>
     */
    const GET = 0;
    /**
     * <code>ACTIVATE = 1;</code>
     */
    const ACTIVATE = 1;
    /**
     * <code>DEACTIVATE = 2;</code>
     */
    const DEACTIVATE = 2;
}

