<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AlarmMember</code>
 */
class AlarmMember extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * memberID is the ID of the member associated with the raised alarm.
     * </pre>
     *
     * <code>uint64 memberID = 1;</code>
     */
    private $memberID = 0;
    /**
     * <pre>
     * alarm is the type of alarm which has been raised.
     * </pre>
     *
     * <code>.etcdserverpb.AlarmType alarm = 2;</code>
     */
    private $alarm = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * memberID is the ID of the member associated with the raised alarm.
     * </pre>
     *
     * <code>uint64 memberID = 1;</code>
     */
    public function getMemberID()
    {
        return $this->memberID;
    }

    /**
     * <pre>
     * memberID is the ID of the member associated with the raised alarm.
     * </pre>
     *
     * <code>uint64 memberID = 1;</code>
     */
    public function setMemberID($var)
    {
        GPBUtil::checkUint64($var);
        $this->memberID = $var;
    }

    /**
     * <pre>
     * alarm is the type of alarm which has been raised.
     * </pre>
     *
     * <code>.etcdserverpb.AlarmType alarm = 2;</code>
     */
    public function getAlarm()
    {
        return $this->alarm;
    }

    /**
     * <pre>
     * alarm is the type of alarm which has been raised.
     * </pre>
     *
     * <code>.etcdserverpb.AlarmType alarm = 2;</code>
     */
    public function setAlarm($var)
    {
        GPBUtil::checkEnum($var, \Etcdserverpb\AlarmType::class);
        $this->alarm = $var;
    }

}

