<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AlarmResponse</code>
 */
class AlarmResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <pre>
     * alarms is a list of alarms associated with the alarm request.
     * </pre>
     *
     * <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     */
    private $alarms;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <pre>
     * alarms is a list of alarms associated with the alarm request.
     * </pre>
     *
     * <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     */
    public function getAlarms()
    {
        return $this->alarms;
    }

    /**
     * <pre>
     * alarms is a list of alarms associated with the alarm request.
     * </pre>
     *
     * <code>repeated .etcdserverpb.AlarmMember alarms = 2;</code>
     */
    public function setAlarms(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcdserverpb\AlarmMember::class);
        $this->alarms = $arr;
    }

}

