<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AuthDisableRequest</code>
 */
class AuthDisableRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

}

