<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AuthenticateResponse</code>
 */
class AuthenticateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <pre>
     * token is an authorized token that can be used in succeeding RPCs
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    private $token = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <pre>
     * token is an authorized token that can be used in succeeding RPCs
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * <pre>
     * token is an authorized token that can be used in succeeding RPCs
     * </pre>
     *
     * <code>string token = 2;</code>
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;
    }

}

