<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AuthRoleGrantPermissionRequest</code>
 */
class AuthRoleGrantPermissionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    private $perm = null;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public function getPerm()
    {
        return $this->perm;
    }

    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public function setPerm(&$var)
    {
        GPBUtil::checkMessage($var, \Authpb\Permission::class);
        $this->perm = $var;
    }

}

