<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AuthUserGrantRoleRequest</code>
 */
class AuthUserGrantRoleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * user is the name of the user which should be granted a given role.
     * </pre>
     *
     * <code>string user = 1;</code>
     */
    private $user = '';
    /**
     * <pre>
     * role is the name of the role to grant to the user.
     * </pre>
     *
     * <code>string role = 2;</code>
     */
    private $role = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * user is the name of the user which should be granted a given role.
     * </pre>
     *
     * <code>string user = 1;</code>
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * <pre>
     * user is the name of the user which should be granted a given role.
     * </pre>
     *
     * <code>string user = 1;</code>
     */
    public function setUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->user = $var;
    }

    /**
     * <pre>
     * role is the name of the role to grant to the user.
     * </pre>
     *
     * <code>string role = 2;</code>
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * <pre>
     * role is the name of the role to grant to the user.
     * </pre>
     *
     * <code>string role = 2;</code>
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;
    }

}

