<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AuthRoleRevokePermissionRequest</code>
 */
class AuthRoleRevokePermissionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string role = 1;</code>
     */
    private $role = '';
    /**
     * <code>string key = 2;</code>
     */
    private $key = '';
    /**
     * <code>string range_end = 3;</code>
     */
    private $range_end = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string role = 1;</code>
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * <code>string role = 1;</code>
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;
    }

    /**
     * <code>string key = 2;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>string key = 2;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;
    }

    /**
     * <code>string range_end = 3;</code>
     */
    public function getRangeEnd()
    {
        return $this->range_end;
    }

    /**
     * <code>string range_end = 3;</code>
     */
    public function setRangeEnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->range_end = $var;
    }

}

