<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.AuthRoleGetRequest</code>
 */
class AuthRoleGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string role = 1;</code>
     */
    private $role = '';

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>string role = 1;</code>
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * <code>string role = 1;</code>
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;
    }

}

