<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf enum <code>etcdserverpb.Compare.CompareResult</code>
 */
class Compare_CompareResult
{
    /**
     * <code>EQUAL = 0;</code>
     */
    const EQUAL = 0;
    /**
     * <code>GREATER = 1;</code>
     */
    const GREATER = 1;
    /**
     * <code>LESS = 2;</code>
     */
    const LESS = 2;
    /**
     * <code>NOT_EQUAL = 3;</code>
     */
    const NOT_EQUAL = 3;
}

