<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf enum <code>etcdserverpb.Compare.CompareTarget</code>
 */
class Compare_CompareTarget
{
    /**
     * <code>VERSION = 0;</code>
     */
    const VERSION = 0;
    /**
     * <code>CREATE = 1;</code>
     */
    const CREATE = 1;
    /**
     * <code>MOD = 2;</code>
     */
    const MOD = 2;
    /**
     * <code>VALUE = 3;</code>
     */
    const VALUE = 3;
}

