<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.DeleteRangeResponse</code>
 */
class DeleteRangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <pre>
     * deleted is the number of keys deleted by the delete range request.
     * </pre>
     *
     * <code>int64 deleted = 2;</code>
     */
    private $deleted = 0;
    /**
     * <pre>
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     * </pre>
     *
     * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
     */
    private $prev_kvs;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <pre>
     * deleted is the number of keys deleted by the delete range request.
     * </pre>
     *
     * <code>int64 deleted = 2;</code>
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * <pre>
     * deleted is the number of keys deleted by the delete range request.
     * </pre>
     *
     * <code>int64 deleted = 2;</code>
     */
    public function setDeleted($var)
    {
        GPBUtil::checkInt64($var);
        $this->deleted = $var;
    }

    /**
     * <pre>
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     * </pre>
     *
     * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
     */
    public function getPrevKvs()
    {
        return $this->prev_kvs;
    }

    /**
     * <pre>
     * if prev_kv is set in the request, the previous key-value pairs will be returned.
     * </pre>
     *
     * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
     */
    public function setPrevKvs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mvccpb\KeyValue::class);
        $this->prev_kvs = $arr;
    }

}

