<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.LeaseGrantRequest</code>
 */
class LeaseGrantRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * TTL is the advisory time-to-live in seconds.
     * </pre>
     *
     * <code>int64 TTL = 1;</code>
     */
    private $TTL = 0;
    /**
     * <pre>
     * ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     * </pre>
     *
     * <code>int64 ID = 2;</code>
     */
    private $ID = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * TTL is the advisory time-to-live in seconds.
     * </pre>
     *
     * <code>int64 TTL = 1;</code>
     */
    public function getTTL()
    {
        return $this->TTL;
    }

    /**
     * <pre>
     * TTL is the advisory time-to-live in seconds.
     * </pre>
     *
     * <code>int64 TTL = 1;</code>
     */
    public function setTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->TTL = $var;
    }

    /**
     * <pre>
     * ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     * </pre>
     *
     * <code>int64 ID = 2;</code>
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * <pre>
     * ID is the requested ID for the lease. If ID is set to 0, the lessor chooses an ID.
     * </pre>
     *
     * <code>int64 ID = 2;</code>
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;
    }

}

