<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.LeaseTimeToLiveRequest</code>
 */
class LeaseTimeToLiveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * ID is the lease ID for the lease.
     * </pre>
     *
     * <code>int64 ID = 1;</code>
     */
    private $ID = 0;
    /**
     * <pre>
     * keys is true to query all the keys attached to this lease.
     * </pre>
     *
     * <code>bool keys = 2;</code>
     */
    private $keys = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * ID is the lease ID for the lease.
     * </pre>
     *
     * <code>int64 ID = 1;</code>
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * <pre>
     * ID is the lease ID for the lease.
     * </pre>
     *
     * <code>int64 ID = 1;</code>
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;
    }

    /**
     * <pre>
     * keys is true to query all the keys attached to this lease.
     * </pre>
     *
     * <code>bool keys = 2;</code>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * <pre>
     * keys is true to query all the keys attached to this lease.
     * </pre>
     *
     * <code>bool keys = 2;</code>
     */
    public function setKeys($var)
    {
        GPBUtil::checkBool($var);
        $this->keys = $var;
    }

}

