<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.LeaseRevokeRequest</code>
 */
class LeaseRevokeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * ID is the lease ID to revoke. When the ID is revoked, all associated keys will be deleted.
     * </pre>
     *
     * <code>int64 ID = 1;</code>
     */
    private $ID = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * ID is the lease ID to revoke. When the ID is revoked, all associated keys will be deleted.
     * </pre>
     *
     * <code>int64 ID = 1;</code>
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * <pre>
     * ID is the lease ID to revoke. When the ID is revoked, all associated keys will be deleted.
     * </pre>
     *
     * <code>int64 ID = 1;</code>
     */
    public function setID($var)
    {
        GPBUtil::checkInt64($var);
        $this->ID = $var;
    }

}

