<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.Member</code>
 */
class Member extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * ID is the member ID for this member.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     */
    private $ID = 0;
    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     */
    private $peerURLs;
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     */
    private $clientURLs;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * ID is the member ID for this member.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * <pre>
     * ID is the member ID for this member.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     */
    public function setID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ID = $var;
    }

    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     */
    public function getPeerURLs()
    {
        return $this->peerURLs;
    }

    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     */
    public function setPeerURLs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peerURLs = $arr;
    }

    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     */
    public function getClientURLs()
    {
        return $this->clientURLs;
    }

    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     */
    public function setClientURLs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->clientURLs = $arr;
    }

}

