<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.MemberAddRequest</code>
 */
class MemberAddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 1;</code>
     */
    private $peerURLs;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 1;</code>
     */
    public function getPeerURLs()
    {
        return $this->peerURLs;
    }

    /**
     * <pre>
     * peerURLs is the list of URLs the added member will use to communicate with the cluster.
     * </pre>
     *
     * <code>repeated string peerURLs = 1;</code>
     */
    public function setPeerURLs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peerURLs = $arr;
    }

}

