<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.PutRequest</code>
 */
class PutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * key is the key, in bytes, to put into the key-value store.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * <pre>
     * value is the value, in bytes, to associate with the key in the key-value store.
     * </pre>
     *
     * <code>bytes value = 2;</code>
     */
    private $value = '';
    /**
     * <pre>
     * lease is the lease ID to associate with the key in the key-value store. A lease
     * value of 0 indicates no lease.
     * </pre>
     *
     * <code>int64 lease = 3;</code>
     */
    private $lease = 0;
    /**
     * <pre>
     * If prev_kv is set, etcd gets the previous key-value pair before changing it.
     * The previous key-value pair will be returned in the put response.
     * </pre>
     *
     * <code>bool prev_kv = 4;</code>
     */
    private $prev_kv = false;
    /**
     * <pre>
     * If ignore_value is set, etcd updates the key using its current value.
     * Returns an error if the key does not exist.
     * </pre>
     *
     * <code>bool ignore_value = 5;</code>
     */
    private $ignore_value = false;
    /**
     * <pre>
     * If ignore_lease is set, etcd updates the key using its current lease.
     * Returns an error if the key does not exist.
     * </pre>
     *
     * <code>bool ignore_lease = 6;</code>
     */
    private $ignore_lease = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * key is the key, in bytes, to put into the key-value store.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <pre>
     * key is the key, in bytes, to put into the key-value store.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    /**
     * <pre>
     * value is the value, in bytes, to associate with the key in the key-value store.
     * </pre>
     *
     * <code>bytes value = 2;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <pre>
     * value is the value, in bytes, to associate with the key in the key-value store.
     * </pre>
     *
     * <code>bytes value = 2;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;
    }

    /**
     * <pre>
     * lease is the lease ID to associate with the key in the key-value store. A lease
     * value of 0 indicates no lease.
     * </pre>
     *
     * <code>int64 lease = 3;</code>
     */
    public function getLease()
    {
        return $this->lease;
    }

    /**
     * <pre>
     * lease is the lease ID to associate with the key in the key-value store. A lease
     * value of 0 indicates no lease.
     * </pre>
     *
     * <code>int64 lease = 3;</code>
     */
    public function setLease($var)
    {
        GPBUtil::checkInt64($var);
        $this->lease = $var;
    }

    /**
     * <pre>
     * If prev_kv is set, etcd gets the previous key-value pair before changing it.
     * The previous key-value pair will be returned in the put response.
     * </pre>
     *
     * <code>bool prev_kv = 4;</code>
     */
    public function getPrevKv()
    {
        return $this->prev_kv;
    }

    /**
     * <pre>
     * If prev_kv is set, etcd gets the previous key-value pair before changing it.
     * The previous key-value pair will be returned in the put response.
     * </pre>
     *
     * <code>bool prev_kv = 4;</code>
     */
    public function setPrevKv($var)
    {
        GPBUtil::checkBool($var);
        $this->prev_kv = $var;
    }

    /**
     * <pre>
     * If ignore_value is set, etcd updates the key using its current value.
     * Returns an error if the key does not exist.
     * </pre>
     *
     * <code>bool ignore_value = 5;</code>
     */
    public function getIgnoreValue()
    {
        return $this->ignore_value;
    }

    /**
     * <pre>
     * If ignore_value is set, etcd updates the key using its current value.
     * Returns an error if the key does not exist.
     * </pre>
     *
     * <code>bool ignore_value = 5;</code>
     */
    public function setIgnoreValue($var)
    {
        GPBUtil::checkBool($var);
        $this->ignore_value = $var;
    }

    /**
     * <pre>
     * If ignore_lease is set, etcd updates the key using its current lease.
     * Returns an error if the key does not exist.
     * </pre>
     *
     * <code>bool ignore_lease = 6;</code>
     */
    public function getIgnoreLease()
    {
        return $this->ignore_lease;
    }

    /**
     * <pre>
     * If ignore_lease is set, etcd updates the key using its current lease.
     * Returns an error if the key does not exist.
     * </pre>
     *
     * <code>bool ignore_lease = 6;</code>
     */
    public function setIgnoreLease($var)
    {
        GPBUtil::checkBool($var);
        $this->ignore_lease = $var;
    }

}

