<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf enum <code>etcdserverpb.RangeRequest.SortOrder</code>
 */
class RangeRequest_SortOrder
{
    /**
     * <pre>
     * default, no sorting
     * </pre>
     *
     * <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * <pre>
     * lowest target value first
     * </pre>
     *
     * <code>ASCEND = 1;</code>
     */
    const ASCEND = 1;
    /**
     * <pre>
     * highest target value first
     * </pre>
     *
     * <code>DESCEND = 2;</code>
     */
    const DESCEND = 2;
}

