<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.RangeResponse</code>
 */
class RangeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <pre>
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     * </pre>
     *
     * <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     */
    private $kvs;
    /**
     * <pre>
     * more indicates if there are more keys to return in the requested range.
     * </pre>
     *
     * <code>bool more = 3;</code>
     */
    private $more = false;
    /**
     * <pre>
     * count is set to the number of keys within the range when requested.
     * </pre>
     *
     * <code>int64 count = 4;</code>
     */
    private $count = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <pre>
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     * </pre>
     *
     * <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     */
    public function getKvs()
    {
        return $this->kvs;
    }

    /**
     * <pre>
     * kvs is the list of key-value pairs matched by the range request.
     * kvs is empty when count is requested.
     * </pre>
     *
     * <code>repeated .mvccpb.KeyValue kvs = 2;</code>
     */
    public function setKvs(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Mvccpb\KeyValue::class);
        $this->kvs = $arr;
    }

    /**
     * <pre>
     * more indicates if there are more keys to return in the requested range.
     * </pre>
     *
     * <code>bool more = 3;</code>
     */
    public function getMore()
    {
        return $this->more;
    }

    /**
     * <pre>
     * more indicates if there are more keys to return in the requested range.
     * </pre>
     *
     * <code>bool more = 3;</code>
     */
    public function setMore($var)
    {
        GPBUtil::checkBool($var);
        $this->more = $var;
    }

    /**
     * <pre>
     * count is set to the number of keys within the range when requested.
     * </pre>
     *
     * <code>int64 count = 4;</code>
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * <pre>
     * count is set to the number of keys within the range when requested.
     * </pre>
     *
     * <code>int64 count = 4;</code>
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;
    }

}

