<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf enum <code>etcdserverpb.RangeRequest.SortTarget</code>
 */
class RangeRequest_SortTarget
{
    /**
     * <code>KEY = 0;</code>
     */
    const KEY = 0;
    /**
     * <code>VERSION = 1;</code>
     */
    const VERSION = 1;
    /**
     * <code>CREATE = 2;</code>
     */
    const CREATE = 2;
    /**
     * <code>MOD = 3;</code>
     */
    const MOD = 3;
    /**
     * <code>VALUE = 4;</code>
     */
    const VALUE = 4;
}

