<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.RequestOp</code>
 */
class RequestOp extends \Google\Protobuf\Internal\Message
{
    protected $request;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     */
    public function getRequestRange()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.etcdserverpb.RangeRequest request_range = 1;</code>
     */
    public function setRequestRange(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\RangeRequest::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.etcdserverpb.PutRequest request_put = 2;</code>
     */
    public function getRequestPut()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.etcdserverpb.PutRequest request_put = 2;</code>
     */
    public function setRequestPut(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\PutRequest::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     */
    public function getRequestDeleteRange()
    {
        return $this->readOneof(3);
    }

    /**
     * <code>.etcdserverpb.DeleteRangeRequest request_delete_range = 3;</code>
     */
    public function setRequestDeleteRange(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\DeleteRangeRequest::class);
        $this->writeOneof(3, $var);
    }

    public function getRequest()
    {
        return $this->whichOneof("request");
    }

}

