<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.ResponseOp</code>
 */
class ResponseOp extends \Google\Protobuf\Internal\Message
{
    protected $response;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public function getResponseRange()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.etcdserverpb.RangeResponse response_range = 1;</code>
     */
    public function setResponseRange(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\RangeResponse::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public function getResponsePut()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.etcdserverpb.PutResponse response_put = 2;</code>
     */
    public function setResponsePut(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\PutResponse::class);
        $this->writeOneof(2, $var);
    }

    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public function getResponseDeleteRange()
    {
        return $this->readOneof(3);
    }

    /**
     * <code>.etcdserverpb.DeleteRangeResponse response_delete_range = 3;</code>
     */
    public function setResponseDeleteRange(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\DeleteRangeResponse::class);
        $this->writeOneof(3, $var);
    }

    public function getResponse()
    {
        return $this->whichOneof("response");
    }

}

