<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.ResponseHeader</code>
 */
class ResponseHeader extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * cluster_id is the ID of the cluster which sent the response.
     * </pre>
     *
     * <code>uint64 cluster_id = 1;</code>
     */
    private $cluster_id = 0;
    /**
     * <pre>
     * member_id is the ID of the member which sent the response.
     * </pre>
     *
     * <code>uint64 member_id = 2;</code>
     */
    private $member_id = 0;
    /**
     * <pre>
     * revision is the key-value store revision when the request was applied.
     * </pre>
     *
     * <code>int64 revision = 3;</code>
     */
    private $revision = 0;
    /**
     * <pre>
     * raft_term is the raft term when the request was applied.
     * </pre>
     *
     * <code>uint64 raft_term = 4;</code>
     */
    private $raft_term = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * cluster_id is the ID of the cluster which sent the response.
     * </pre>
     *
     * <code>uint64 cluster_id = 1;</code>
     */
    public function getClusterId()
    {
        return $this->cluster_id;
    }

    /**
     * <pre>
     * cluster_id is the ID of the cluster which sent the response.
     * </pre>
     *
     * <code>uint64 cluster_id = 1;</code>
     */
    public function setClusterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->cluster_id = $var;
    }

    /**
     * <pre>
     * member_id is the ID of the member which sent the response.
     * </pre>
     *
     * <code>uint64 member_id = 2;</code>
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * <pre>
     * member_id is the ID of the member which sent the response.
     * </pre>
     *
     * <code>uint64 member_id = 2;</code>
     */
    public function setMemberId($var)
    {
        GPBUtil::checkUint64($var);
        $this->member_id = $var;
    }

    /**
     * <pre>
     * revision is the key-value store revision when the request was applied.
     * </pre>
     *
     * <code>int64 revision = 3;</code>
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * <pre>
     * revision is the key-value store revision when the request was applied.
     * </pre>
     *
     * <code>int64 revision = 3;</code>
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;
    }

    /**
     * <pre>
     * raft_term is the raft term when the request was applied.
     * </pre>
     *
     * <code>uint64 raft_term = 4;</code>
     */
    public function getRaftTerm()
    {
        return $this->raft_term;
    }

    /**
     * <pre>
     * raft_term is the raft term when the request was applied.
     * </pre>
     *
     * <code>uint64 raft_term = 4;</code>
     */
    public function setRaftTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->raft_term = $var;
    }

}

