<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.TxnResponse</code>
 */
class TxnResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    private $header = null;
    /**
     * <pre>
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     * </pre>
     *
     * <code>bool succeeded = 2;</code>
     */
    private $succeeded = false;
    /**
     * <pre>
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     * </pre>
     *
     * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     */
    private $responses;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * <code>.etcdserverpb.ResponseHeader header = 1;</code>
     */
    public function setHeader(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\ResponseHeader::class);
        $this->header = $var;
    }

    /**
     * <pre>
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     * </pre>
     *
     * <code>bool succeeded = 2;</code>
     */
    public function getSucceeded()
    {
        return $this->succeeded;
    }

    /**
     * <pre>
     * succeeded is set to true if the compare evaluated to true or false otherwise.
     * </pre>
     *
     * <code>bool succeeded = 2;</code>
     */
    public function setSucceeded($var)
    {
        GPBUtil::checkBool($var);
        $this->succeeded = $var;
    }

    /**
     * <pre>
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     * </pre>
     *
     * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * <pre>
     * responses is a list of responses corresponding to the results from applying
     * success if succeeded is true or failure if succeeded is false.
     * </pre>
     *
     * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
     */
    public function setResponses(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Etcdserverpb\ResponseOp::class);
        $this->responses = $arr;
    }

}

