<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.WatchCreateRequest</code>
 */
class WatchCreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * key is the key to register for watching.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     */
    private $key = '';
    /**
     * <pre>
     * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * </pre>
     *
     * <code>bytes range_end = 2;</code>
     */
    private $range_end = '';
    /**
     * <pre>
     * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * </pre>
     *
     * <code>int64 start_revision = 3;</code>
     */
    private $start_revision = 0;
    /**
     * <pre>
     * progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * </pre>
     *
     * <code>bool progress_notify = 4;</code>
     */
    private $progress_notify = false;
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     */
    private $filters;
    /**
     * <pre>
     * If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * </pre>
     *
     * <code>bool prev_kv = 6;</code>
     */
    private $prev_kv = false;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * key is the key to register for watching.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <pre>
     * key is the key to register for watching.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    /**
     * <pre>
     * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * </pre>
     *
     * <code>bytes range_end = 2;</code>
     */
    public function getRangeEnd()
    {
        return $this->range_end;
    }

    /**
     * <pre>
     * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * </pre>
     *
     * <code>bytes range_end = 2;</code>
     */
    public function setRangeEnd($var)
    {
        GPBUtil::checkString($var, False);
        $this->range_end = $var;
    }

    /**
     * <pre>
     * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * </pre>
     *
     * <code>int64 start_revision = 3;</code>
     */
    public function getStartRevision()
    {
        return $this->start_revision;
    }

    /**
     * <pre>
     * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * </pre>
     *
     * <code>int64 start_revision = 3;</code>
     */
    public function setStartRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_revision = $var;
    }

    /**
     * <pre>
     * progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * </pre>
     *
     * <code>bool progress_notify = 4;</code>
     */
    public function getProgressNotify()
    {
        return $this->progress_notify;
    }

    /**
     * <pre>
     * progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * </pre>
     *
     * <code>bool progress_notify = 4;</code>
     */
    public function setProgressNotify($var)
    {
        GPBUtil::checkBool($var);
        $this->progress_notify = $var;
    }

    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     */
    public function setFilters(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Etcdserverpb\WatchCreateRequest_FilterType::class);
        $this->filters = $arr;
    }

    /**
     * <pre>
     * If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * </pre>
     *
     * <code>bool prev_kv = 6;</code>
     */
    public function getPrevKv()
    {
        return $this->prev_kv;
    }

    /**
     * <pre>
     * If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * </pre>
     *
     * <code>bool prev_kv = 6;</code>
     */
    public function setPrevKv($var)
    {
        GPBUtil::checkBool($var);
        $this->prev_kv = $var;
    }

}

