<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.WatchCancelRequest</code>
 */
class WatchCancelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * watch_id is the watcher id to cancel so that no more events are transmitted.
     * </pre>
     *
     * <code>int64 watch_id = 1;</code>
     */
    private $watch_id = 0;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * watch_id is the watcher id to cancel so that no more events are transmitted.
     * </pre>
     *
     * <code>int64 watch_id = 1;</code>
     */
    public function getWatchId()
    {
        return $this->watch_id;
    }

    /**
     * <pre>
     * watch_id is the watcher id to cancel so that no more events are transmitted.
     * </pre>
     *
     * <code>int64 watch_id = 1;</code>
     */
    public function setWatchId($var)
    {
        GPBUtil::checkInt64($var);
        $this->watch_id = $var;
    }

}

