<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>etcdserverpb.WatchRequest</code>
 */
class WatchRequest extends \Google\Protobuf\Internal\Message
{
    protected $request_union;

    public function __construct() {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
     */
    public function getCreateRequest()
    {
        return $this->readOneof(1);
    }

    /**
     * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
     */
    public function setCreateRequest(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\WatchCreateRequest::class);
        $this->writeOneof(1, $var);
    }

    /**
     * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
     */
    public function getCancelRequest()
    {
        return $this->readOneof(2);
    }

    /**
     * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
     */
    public function setCancelRequest(&$var)
    {
        GPBUtil::checkMessage($var, \Etcdserverpb\WatchCancelRequest::class);
        $this->writeOneof(2, $var);
    }

    public function getRequestUnion()
    {
        return $this->whichOneof("request_union");
    }

}

