<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

namespace Etcdserverpb;

/**
 * Protobuf enum <code>etcdserverpb.WatchCreateRequest.FilterType</code>
 */
class WatchCreateRequest_FilterType
{
    /**
     * <pre>
     * filter out put event.
     * </pre>
     *
     * <code>NOPUT = 0;</code>
     */
    const NOPUT = 0;
    /**
     * <pre>
     * filter out delete event.
     * </pre>
     *
     * <code>NODELETE = 1;</code>
     */
    const NODELETE = 1;
}

