<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Authpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Permission is a single entity
 * </pre>
 *
 * Protobuf type <code>authpb.Permission</code>
 */
class Permission extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.authpb.Permission.Type permType = 1;</code>
     */
    private $permType = 0;
    /**
     * <code>bytes key = 2;</code>
     */
    private $key = '';
    /**
     * <code>bytes range_end = 3;</code>
     */
    private $range_end = '';

    public function __construct() {
        \GPBMetadata\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <code>.authpb.Permission.Type permType = 1;</code>
     */
    public function getPermType()
    {
        return $this->permType;
    }

    /**
     * <code>.authpb.Permission.Type permType = 1;</code>
     */
    public function setPermType($var)
    {
        GPBUtil::checkEnum($var, \Authpb\Permission_Type::class);
        $this->permType = $var;
    }

    /**
     * <code>bytes key = 2;</code>
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * <code>bytes key = 2;</code>
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    /**
     * <code>bytes range_end = 3;</code>
     */
    public function getRangeEnd()
    {
        return $this->range_end;
    }

    /**
     * <code>bytes range_end = 3;</code>
     */
    public function setRangeEnd($var)
    {
        GPBUtil::checkString($var, False);
        $this->range_end = $var;
    }

}

