<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Authpb;

/**
 * Protobuf enum <code>authpb.Permission.Type</code>
 */
class Permission_Type
{
    /**
     * <code>READ = 0;</code>
     */
    const READ = 0;
    /**
     * <code>WRITE = 1;</code>
     */
    const WRITE = 1;
    /**
     * <code>READWRITE = 2;</code>
     */
    const READWRITE = 2;
}

