<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Authpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * User is a single entry in the bucket authUsers
 * </pre>
 *
 * Protobuf type <code>authpb.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bytes name = 1;</code>
     */
    private $name = '';
    /**
     * <code>bytes password = 2;</code>
     */
    private $password = '';
    /**
     * <code>repeated string roles = 3;</code>
     */
    private $roles;

    public function __construct() {
        \GPBMetadata\Auth::initOnce();
        parent::__construct();
    }

    /**
     * <code>bytes name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>bytes name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;
    }

    /**
     * <code>bytes password = 2;</code>
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * <code>bytes password = 2;</code>
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;
    }

    /**
     * <code>repeated string roles = 3;</code>
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * <code>repeated string roles = 3;</code>
     */
    public function setRoles(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->roles = $arr;
    }

}

